-- MySQL Script generated by MySQL Workbench
-- Fri Sep  2 14:07:10 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dulich
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dulich
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dulich` DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci ;
USE `dulich` ;

-- -----------------------------------------------------
-- Table `dulich`.`daily`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dulich`.`daily` (
  `MSDL` INT NOT NULL,
  `TENDL` VARCHAR(45) NULL DEFAULT NULL,
  `MANVQL` INT NULL DEFAULT NULL,
  `DIACHIDL` VARCHAR(255) NULL DEFAULT NULL,
  `SDTDL` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`MSDL`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `dulich`.`khachsan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dulich`.`khachsan` (
  `MSKS` INT NOT NULL,
  `TENKS` VARCHAR(45) NULL DEFAULT NULL,
  `DIACHI` VARCHAR(255) NULL DEFAULT NULL,
  `SDTKS` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`MSKS`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `dulich`.`tinh`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dulich`.`tinh` (
  `MST` INT NOT NULL,
  `TENTINH` VARCHAR(45) NULL DEFAULT NULL,
  `khachsan_MSKS` INT NOT NULL,
  PRIMARY KEY (`MST`, `khachsan_MSKS`),
  INDEX `fk_tinh_khachsan1_idx` (`khachsan_MSKS` ASC) VISIBLE,
  CONSTRAINT `fk_tinh_khachsan1`
    FOREIGN KEY (`khachsan_MSKS`)
    REFERENCES `dulich`.`khachsan` (`MSKS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `dulich`.`diadiem_thamquan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dulich`.`diadiem_thamquan` (
  `MSDD` INT NOT NULL,
  `TENDD` VARCHAR(45) NULL DEFAULT NULL,
  `DIACHI` VARCHAR(255) NULL DEFAULT NULL,
  `tinh_MST` INT NOT NULL,
  PRIMARY KEY (`MSDD`, `tinh_MST`),
  INDEX `fk_diadiem_thamquan_tinh1_idx` (`tinh_MST` ASC) VISIBLE,
  CONSTRAINT `fk_diadiem_thamquan_tinh1`
    FOREIGN KEY (`tinh_MST`)
    REFERENCES `dulich`.`tinh` (`MST`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `dulich`.`login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dulich`.`login` (
  `Login_id` INT NOT NULL AUTO_INCREMENT,
  `LoginLoai` VARCHAR(45) NULL DEFAULT NULL,
  `LoginUser` VARCHAR(45) NOT NULL,
  `LoginPass` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Login_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `dulich`.`khachang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dulich`.`khachang` (
  `MSKH` INT NOT NULL,
  `TENKH` VARCHAR(45) NULL DEFAULT NULL,
  `Login_id` INT NULL DEFAULT NULL,
  `GIOITINH` VARCHAR(45) NULL DEFAULT NULL,
  `CCCD` VARCHAR(45) NULL DEFAULT NULL,
  `DIACHI` VARCHAR(255) NULL DEFAULT NULL,
  `SDT` VARCHAR(45) NULL DEFAULT NULL,
  `login_Login_id` INT NOT NULL,
  PRIMARY KEY (`MSKH`, `login_Login_id`),
  INDEX `fk_khachang_login1_idx` (`login_Login_id` ASC) VISIBLE,
  CONSTRAINT `fk_khachang_login1`
    FOREIGN KEY (`login_Login_id`)
    REFERENCES `dulich`.`login` (`Login_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `dulich`.`nhanvien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dulich`.`nhanvien` (
  `MSNV` INT NOT NULL,
  `TENNV` VARCHAR(45) NULL DEFAULT NULL,
  `Login_id` INT NULL DEFAULT NULL,
  `NGAYSINH` DATETIME NULL DEFAULT NULL,
  `GIOITINH` VARCHAR(45) NULL DEFAULT NULL,
  `DIACHI` VARCHAR(255) NULL DEFAULT NULL,
  `SDTNV` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`MSNV`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `dulich`.`phuongtien`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dulich`.`phuongtien` (
  `MSPT` INT NOT NULL,
  `LOAIPT` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`MSPT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `dulich`.`ve`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dulich`.`ve` (
  `MSVE` INT NOT NULL,
  `MSTOUR` INT NOT NULL,
  `MSDL` INT NOT NULL,
  `daily_MSDL` INT NOT NULL,
  `khachang_MSKH` INT NOT NULL,
  PRIMARY KEY (`MSVE`, `MSTOUR`, `MSDL`, `daily_MSDL`, `khachang_MSKH`),
  INDEX `fk_ve_daily1_idx` (`daily_MSDL` ASC) VISIBLE,
  INDEX `fk_ve_khachang1_idx` (`khachang_MSKH` ASC) VISIBLE,
  CONSTRAINT `fk_ve_daily1`
    FOREIGN KEY (`daily_MSDL`)
    REFERENCES `dulich`.`daily` (`MSDL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ve_khachang1`
    FOREIGN KEY (`khachang_MSKH`)
    REFERENCES `dulich`.`khachang` (`MSKH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `dulich`.`tour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dulich`.`tour` (
  `MSTOUR` INT NOT NULL,
  `TENTOUR` VARCHAR(45) NULL DEFAULT NULL,
  `NGAYBD` DATETIME NULL DEFAULT NULL,
  `NGAYKT` DATETIME NULL DEFAULT NULL,
  `GIA` DECIMAL(10,0) NULL DEFAULT '0',
  `phuongtien_MSPT` INT NOT NULL,
  `ve_MSVE` INT NOT NULL,
  `ve_MSTOUR` INT NOT NULL,
  `ve_MSDL` INT NOT NULL,
  PRIMARY KEY (`MSTOUR`, `phuongtien_MSPT`, `ve_MSVE`, `ve_MSTOUR`, `ve_MSDL`),
  INDEX `fk_tour_phuongtien1_idx` (`phuongtien_MSPT` ASC) VISIBLE,
  INDEX `fk_tour_ve1_idx` (`ve_MSVE` ASC, `ve_MSTOUR` ASC, `ve_MSDL` ASC) VISIBLE,
  CONSTRAINT `fk_tour_phuongtien1`
    FOREIGN KEY (`phuongtien_MSPT`)
    REFERENCES `dulich`.`phuongtien` (`MSPT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tour_ve1`
    FOREIGN KEY (`ve_MSVE` , `ve_MSTOUR` , `ve_MSDL`)
    REFERENCES `dulich`.`ve` (`MSVE` , `MSTOUR` , `MSDL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `dulich`.`KH_DangKy_Tour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dulich`.`KH_DangKy_Tour` (
  `tour_MSTOUR` INT NOT NULL,
  `khachang_MSKH` INT NOT NULL,
  PRIMARY KEY (`tour_MSTOUR`, `khachang_MSKH`),
  INDEX `fk_tour_has_khachang_khachang1_idx` (`khachang_MSKH` ASC) VISIBLE,
  INDEX `fk_tour_has_khachang_tour_idx` (`tour_MSTOUR` ASC) VISIBLE,
  CONSTRAINT `fk_tour_has_khachang_tour`
    FOREIGN KEY (`tour_MSTOUR`)
    REFERENCES `dulich`.`tour` (`MSTOUR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tour_has_khachang_khachang1`
    FOREIGN KEY (`khachang_MSKH`)
    REFERENCES `dulich`.`khachang` (`MSKH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `dulich`.`DaiLy_QuanLy_Tour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dulich`.`DaiLy_QuanLy_Tour` (
  `tour_has_khachang_tour_MSTOUR` INT NOT NULL,
  `tour_has_khachang_khachang_MSKH` INT NOT NULL,
  `daily_MSDL` INT NOT NULL,
  `So_Luong_Ve` INT NULL,
  PRIMARY KEY (`tour_has_khachang_tour_MSTOUR`, `tour_has_khachang_khachang_MSKH`, `daily_MSDL`),
  INDEX `fk_tour_has_khachang_has_daily_daily1_idx` (`daily_MSDL` ASC) VISIBLE,
  INDEX `fk_tour_has_khachang_has_daily_tour_has_khachang1_idx` (`tour_has_khachang_tour_MSTOUR` ASC, `tour_has_khachang_khachang_MSKH` ASC) VISIBLE,
  CONSTRAINT `fk_tour_has_khachang_has_daily_tour_has_khachang1`
    FOREIGN KEY (`tour_has_khachang_tour_MSTOUR` , `tour_has_khachang_khachang_MSKH`)
    REFERENCES `dulich`.`KH_DangKy_Tour` (`tour_MSTOUR` , `khachang_MSKH`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tour_has_khachang_has_daily_daily1`
    FOREIGN KEY (`daily_MSDL`)
    REFERENCES `dulich`.`daily` (`MSDL`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `dulich`.`Tour_Den_DDThamQuan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dulich`.`Tour_Den_DDThamQuan` (
  `diadiem_thamquan_MSDD` INT NOT NULL,
  `tour_MSTOUR` INT NOT NULL,
  `NgayDen` DATETIME NULL DEFAULT NULL,
  `NgayDi` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`diadiem_thamquan_MSDD`, `tour_MSTOUR`),
  INDEX `fk_diadiem_thamquan_has_tour_tour1_idx` (`tour_MSTOUR` ASC) VISIBLE,
  INDEX `fk_diadiem_thamquan_has_tour_diadiem_thamquan1_idx` (`diadiem_thamquan_MSDD` ASC) VISIBLE,
  CONSTRAINT `fk_diadiem_thamquan_has_tour_diadiem_thamquan1`
    FOREIGN KEY (`diadiem_thamquan_MSDD`)
    REFERENCES `dulich`.`diadiem_thamquan` (`MSDD`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diadiem_thamquan_has_tour_tour1`
    FOREIGN KEY (`tour_MSTOUR`)
    REFERENCES `dulich`.`tour` (`MSTOUR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `dulich`.`khachsan_thuoc_tour`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dulich`.`khachsan_thuoc_tour` (
  `khachsan_MSKS` INT NOT NULL,
  `tour_MSTOUR` INT NOT NULL,
  PRIMARY KEY (`khachsan_MSKS`, `tour_MSTOUR`),
  INDEX `fk_khachsan_has_tour_tour1_idx` (`tour_MSTOUR` ASC) VISIBLE,
  INDEX `fk_khachsan_has_tour_khachsan1_idx` (`khachsan_MSKS` ASC) VISIBLE,
  CONSTRAINT `fk_khachsan_has_tour_khachsan1`
    FOREIGN KEY (`khachsan_MSKS`)
    REFERENCES `dulich`.`khachsan` (`MSKS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_khachsan_has_tour_tour1`
    FOREIGN KEY (`tour_MSTOUR`)
    REFERENCES `dulich`.`tour` (`MSTOUR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
